from node:latest as build

workdir /usr/local/app

copy ./ /usr/local/app

run npm install
run npm run build

from nginx:latest

copy --from=build /usr/local/app/dist/hello-angular /usr/share/nginx/html

expose 80